### ISSUE TITLE
Geos is not getting installed on cedar-14

### ISSUE THREAD

**Issue by bhargavd** [diowa/heroku-buildpack-rgeo-prep#3]
I followed the instructions and these are my buildpacks
Buildpack URLs
1. https://github.com/diowa/heroku-buildpack-rgeo-prep.git
2. https://github.com/peterkeen/heroku-buildpack-vendorbinaries.git
3. heroku/ruby

Also updated the .vendor_urls with these
https://s3.amazonaws.com/diowa-buildpacks/geos-3.7.1-heroku.tar.gz
https://s3.amazonaws.com/diowa-buildpacks/proj-5.2.0-heroku.tar.gz

But I am getting this error when I try to run the shapefiles
RGeo::Error::RGeoError: GEOS is not available, but is required for correct interpretation of polygons in shapefiles.

Also I checked my heroku console and I see
Loading production environment (Rails 4.2.8)
irb(main):001:0> require 'rgeo'
=> false
irb(main):002:0> RGeo::Geos.supported?
=> false
irb(main):003:0> 
Any suggestions or help please

**Comment by tagliala** [comment]
Hi, please try to recompile RGeo

Take a look at https://www.diowa.com/blog/heroku/2016/02/26/using-rgeo-with-geos-on-heroku#4-deploy, step number 4

**Comment by bhargavd** [comment]
Hi , I tried step 4 but still same result I got the same error as before

heroku repo:purge_cache
Running set -e
mkdir -p tmp/repo_tmp/unpack
cd tmp/repo_tmp

cache was cleared.
Redeployed application and adding logs FYI
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> heroku-buildpack-rgeo-prep app detected
remote: -----> VendorBinaries app detected
remote: -----> Found a .vendor_urls file
remote:        Vendoring https://s3.amazonaws.com/diowa-buildpacks/geos-3.7.1-heroku.tar.gz
remote:        Vendoring https://s3.amazonaws.com/diowa-buildpacks/proj-5.2.0-heroku.tar.gz
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.4.4
.
.
remote:        Fetching rgeo 0.5.3
remote:        Installing rgeo 0.5.3 with native extensions

Loading production environment (Rails 4.2.8)
irb(main):001:0> RGeo::Geos.supported?
=> false

**Comment by tagliala** [comment]
Did you set this?

```
heroku config:set LD_LIBRARY_PATH=/app/lib
```

(PS: if you didn't, you have to recompile rgeo)

**Comment by bhargavd** [comment]
Yes I did it before and this my heroku config(there are more but not adding them here)
BUILDPACK_URL:                https://github.com/ddollar/heroku-buildpack-multi.git
LANG:                         en_US.UTF-8
LD_LIBRARY_PATH:              /app/lib
RACK_ENV:                     production
RAILS_ENV:                    production

**Comment by tagliala** [comment]
On which Heroku stack are you?

```
heroku stack
```

**Comment by bhargavd** [comment]
Available Stacks
* cedar-14
I am on cedar-14

**Comment by tagliala** [comment]
Please try the following

### 1. Unset `BUILDPACK_URL`

That is very old stuff.

```
remote: WARNING: This buildpack is no longer maintained.
remote: 
remote: Please choose a different buildpack or go to https://github.com/ddollar/heroku-buildpack-multi
remote: and fork it to your own account.
remote: 
remote: This buildpack will cease to function at the stroke of midnight on January 1, 2017.
```


### 2. Remove `.buildpacks` file from your repo

It is not needed anymore

### 3. Set the buildpacks in the new way

```
heroku buildpacks:set https://github.com/diowa/heroku-buildpack-rgeo-prep.git
heroku buildpacks:add https://github.com/peterkeen/heroku-buildpack-vendorbinaries.git
heroku buildpacks:add heroku/ruby
```

### 4. Use an older versions of GEOS

I do not know exactly why 3.7.1 doesn't work, but I've built it on `heroku-18`. I think that you may try to build newer versions of geos libraries on cedar-14 with by downloading and deploying [Vesuvius](https://github.com/tagliala/vesuvius) by yourself, but `cedar-14` stack is deprecated and will reach EOL [very soon](https://devcenter.heroku.com/articles/cedar-14-stack)

Use this in your `.vendor_urls`
```
https://s3.amazonaws.com/diowa-buildpacks/geos-3.5.0-heroku.tar.gz
```

---

![image](https://user-images.githubusercontent.com/556268/52076661-72516a00-258f-11e9-8cb2-f59889e190d1.png)

Hope it helps

**Comment by bhargavd** [comment]
Thanks @tagliala finally it worked after updating .vendor_urls
`https://s3.amazonaws.com/diowa-buildpacks/geos-3.5.0-heroku.tar.gz`
Loading production environment (Rails 4.2.8)
irb(main):001:0> RGeo::VERSION
=> "0.5.3"
irb(main):002:0> RGeo::Geos.version
=> "3.5.0"
irb(main):003:0> RGeo::Geos.supported?
=> true

**Comment by tagliala** [comment]
👍 closing here
